### ISSUE TITLE
Jaeger: results not refreshing when changing tracked service

### ISSUE THREAD

**Issue by marwonline** [kobsio/kobs#142]
**Describe the bug**

The Jaeger traces are not refreshed when changing the service.

**To Reproduce**

1. Go to http://kobs.demo/jaeger
2. Select any service
3. Click search button
4. Change the service
5. Click search button
6. The URL changes but the results are not updated. The API call still uses the first service. Reloading the page loads the desired traces.

**Expected behavior**

URL changes and triggers change of the traces in the results view.

**Screenshots**

-

**Additional context**

-

**Comment by ricoberger** [comment]
Oh indeed. Thanks for reporting 🙂.

Why is it not surprising to me that you are the first to find and report a bug 😅
