### ISSUE TITLE
[clickhouse] Undesired URL Decode when using ILIKE

### ISSUE THREAD

**Issue by axdotl** [kobsio/kobs#166]
**Describe the bug**

**To Reproduce**

1. Go to `https://<your-kobs-instance>/clickhouse-logging`
2. Enter following into search field `namespace='monitoring' _and_ log=~'%403%'`
3. Execute search (hit Enter or  press search-button)
4. Admire change of search string to `namespace='monitoring' _and_ log=~'@3%'`

**Expected behavior**

When using `ILIKE` its not desired to have percent sequences interpreted as URL encoding

**Screenshots**

![image](https://user-images.githubusercontent.com/9337156/136504044-1a7317ef-d4f6-42c4-860d-6e2b6c550ab9.png)

![image](https://user-images.githubusercontent.com/9337156/136504069-c85c4560-f6e3-42a3-9f7d-4b31dca118d2.png)

**Additional context**

n/a

**Comment by ricoberger** [comment]
Thanks for reporting 🙂. This should be fixed by #168.
