### ISSUE TITLE
Yarn build is failing

### ISSUE THREAD

**Issue by AkshayDubey29** [kobsio/kobs#206]
Can anyone help me to build kobs locally, I am using Mac for this?

![image](https://user-images.githubusercontent.com/14831408/141750043-e0e1c8ac-89f0-4113-b717-9127a5025fd2.png)

**Comment by ricoberger** [comment]
Hi, from the following article it looks like you are running out of memory: https://jcutrer.com/javascript/yarn-build-exit-code-137

You can try to remove the `prebuild` script from the [package.json](https://github.com/kobsio/kobs/blob/main/package.json) file and then run the following commands to build each plugin and finally build the complete app:

```sh
yarn workspace @kobsio/plugin-applications plugin
yarn workspace @kobsio/plugin-clickhouse plugin
yarn workspace @kobsio/plugin-core plugin
yarn workspace @kobsio/plugin-dashboards plugin
yarn workspace @kobsio/plugin-elasticsearch plugin
yarn workspace @kobsio/plugin-flux plugin
yarn workspace @kobsio/plugin-grafana plugin
yarn workspace @kobsio/plugin-istio plugin
yarn workspace @kobsio/plugin-jaeger plugin
yarn workspace @kobsio/plugin-kiali plugin
yarn workspace @kobsio/plugin-markdown plugin
yarn workspace @kobsio/plugin-opsgenie plugin
yarn workspace @kobsio/plugin-prometheus plugin
yarn workspace @kobsio/plugin-resources plugin
yarn workspace @kobsio/plugin-rss plugin
yarn workspace @kobsio/plugin-sonarqube plugin
yarn workspace @kobsio/plugin-sql plugin
yarn workspace @kobsio/plugin-teams plugin
yarn workspace @kobsio/plugin-users plugin

yarn build
```

This would avoid to build the plugins in parallel, which should consume less resources.

**Comment by AkshayDubey29** [comment]
Started getting the below issue:

![image](https://user-images.githubusercontent.com/14831408/142093650-4173a47d-971c-4bc6-b6b3-1caf77ac6f9a.png)

**Comment by AkshayDubey29** [comment]
@ricoberger 

module github.com/kobsio/kobs@latest found (v0.6.0), but does not contain package github.com/kobsio/kobs/plugins/grafana

Any idea what I am missing

**Comment by ricoberger** [comment]
Are you trying to build https://github.com/kobsio/kobs or a custom version of kobs via https://github.com/kobsio/app?

If the latter is the case then you can not use the Grafana plugin, because it's not released yet.

**Comment by ricoberger** [comment]
I would close the issue for now. If you still have issues please let me know.
