### ISSUE TITLE
[klogs-plugin] Query Attributes Autocomplete

### ISSUE THREAD

**Issue by matthiastz** [kobsio/kobs#449]
## Is your feature request related to a problem? Please describe

I'm always frustrated when entering queries over and over, that I have to manually enter each field (attribute). Imho this is unnecessary type-work and can lead to typos etc.  

## Describe the solution you'd like

- dropdown with a list of fields (attributes) that match my input (always on attribute level)
- suggestions could e.g. come from the "fields" (1) area, where the available fields are listed _after_ I run a query,
- or (2) somehow from the Backend API that _knows_ (persistence) which valid fields were used in queries in the past time -> here also some relevance/priority (which fields are used very often) could be integrated as well, but thats just an idea...

Example:
<img width="652" alt="autocomplete-dropdown" src="https://user-images.githubusercontent.com/23010759/210054755-5fe7b5e6-824d-40ea-a814-38759e9709cd.png">

## Describe alternatives you've considered

There are none afaik. You can only manually copy fields or fully queries from e.g. a text field on your computer to Klogs, but there is no autocompletion yet.

**Comment by ricoberger** [comment]
Hi @matthiastz, autocompletion for queries in the klogs plugin was implemented in #472 and should be available in the next version 🙂.
