### ISSUE TITLE
[klogs-plugin] Query History

### ISSUE THREAD

**Issue by matthiastz** [kobsio/kobs#450]
## Is your feature request related to a problem? Please describe

I'm always frustrated when heavily using Klogs that it does not recognize the past queries that I used for searching.

## Describe the solution you'd like

Some kind of Query History that saves the last X (e.g. 10) queries that I used in Klogs.
In the context of the Klogs input field I have some option to select (or better: match) from a list of my past queries (if there are some), select one - and that query gets automatically set as input for the Klogs search.  

## Describe alternatives you've considered

Manually saving Klogs queries on my computer

**Comment by ricoberger** [comment]
Hi @matthiastz, the query history for the klogs plugin was implemented in #539 and should be available in the next version 🙂
