### ISSUE TITLE
[mongodb] Run Aggregations

### ISSUE THREAD

**Issue by jkraml-staffbase** [kobsio/kobs#497]
## Is your feature request related to a problem? Please describe

I'd like to run (non-modifying) aggregation pipelines on MongoDB collections. Currently, only "find" and "count" are available

## Describe the solution you'd like

In the "Query Documents" view, in the "operation" drop-down, I'd like to select the option "aggregate" and then enter an aggregation pipeline in the "query" field.

## Describe alternatives you've considered

Currently, I open a shell in the mongodb container (also via kobs) and do it on the command line.

**Comment by ricoberger** [comment]
Hi @jkraml-staffbase, I added this as acceptance criteria to our rework ticket for MongoDB, so that this feature should be available with the next version.

**Comment by ricoberger** [comment]
Hi @jkraml-staffbase, this was implemented in #527 and should be available in the next version 🙂
